final List<String> availableFontNames = [
  'Open Sans',
  // 'SFNSDisplay',
  // 'CanelaText',
  // 'Charter',
  // 'Palatino',
  // 'ProximaNova',
  'Bitter',
  'Caveat',
  'Comfortaa',
  'CormorantGaramond',
  'FiraSans',
  'Lora',
  'Merriweather',
  'NotoSerif',
  'Nunito',
  'PlayfairDisplay',
  'PTSerif',
  'RobotoSlab',
];
