name: bookflow
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  outline_gradient_button: ^2.0.1+1
  curved_navigation_bar: ^1.0.3
  flutter_switch: ^0.3.2
  firebase_core: ^2.14.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  google_sign_in: ^6.1.4
  # flutter_facebook_auth: ^6.0.0
  sign_in_with_apple: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
      - assets/
      - assets/images/

  fonts: 
      - family: Open Sans
        fonts: 
          - asset: assets/fonts/OpenSansBold.ttf
            weight: 700
          - asset: assets/fonts/OpenSansRegular.ttf
            weight: 400
          - asset: assets/fonts/OpenSansSemiBold.ttf
            weight: 600