name: bookflow
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  outline_gradient_button: ^2.0.1
  curved_navigation_bar: ^1.0.3
  flutter_switch: ^0.3.2
  firebase_core: ^3.13.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  shared_preferences: ^2.2.2
  firebase_performance: ^0.10.1+5
  file_picker: ^10.1.3
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  flutter_spinkit: ^5.2.0
  loading_animation_widget: ^1.2.0
  flutter_animate: ^4.4.0
  animate_gradient: ^0.0.2
  lottie: ^3.1.0
  provider: ^6.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets: 
      - assets/
      - assets/images/
      - assets/animations/

  fonts: 
      - family: Open Sans
        fonts: 
          - asset: assets/fonts/OpenSansBold.ttf
            weight: 700
          - asset: assets/fonts/OpenSansRegular.ttf
            weight: 400
          - asset: assets/fonts/OpenSansSemiBold.ttf
            weight: 600
      - family: SFNSDisplay
        fonts:
          - asset: assets/fonts/SFNSDisplayRegular.otf
      - family: CanelaText
        fonts:
          - asset: assets/fonts/CanelaTextRegular.otf
      - family: Charter
        fonts:
         - asset: assets/fonts/CharterRegular.otf
      - family: Palatino
        fonts:
        - asset: assets/fonts/PalatinoRegular.ttf
      - family: ProximaNova
        fonts:
        - asset: assets/fonts/ProximaNovaRegular.otf
      - family: Bitter
        fonts:
        - asset: assets/fonts/Bitter-Regular.ttf
      - family: Caveat
        fonts:
          - asset: assets/fonts/Caveat-Regular.ttf
      - family: Comfortaa
        fonts:
          - asset: assets/fonts/Comfortaa-Regular.ttf
      - family: CormorantGaramond
        fonts:
          - asset: assets/fonts/CormorantGaramond-Regular.ttf
      - family: FiraSans
        fonts:
          - asset: assets/fonts/FiraSans-Regular.ttf
      - family: Lora
        fonts:
          - asset: assets/fonts/Lora-Regular.ttf
      - family: Merriweather
        fonts:
          - asset: assets/fonts/Merriweather-Regular.ttf
      - family: NotoSerif
        fonts:
          - asset: assets/fonts/NotoSerif-Regular.ttf
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Regular.ttf
      - family: PlayfairDisplay
        fonts:
          - asset: assets/fonts/PlayfairDisplay-Regular.ttf
      - family: PTSerif
        fonts:
          - asset: assets/fonts/PTSerif-Regular.ttf
      - family: RobotoSlab
        fonts:
          - asset: assets/fonts/RobotoSlab-Regular.ttf