name: bookflow
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  outline_gradient_button: ^2.0.1+1
  curved_navigation_bar: ^1.0.3
  flutter_switch: ^0.3.2
  firebase_core: ^2.14.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  shared_preferences: ^2.2.1
  firebase_performance: ^0.9.2+4
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  flutter_spinkit: ^5.2.0
  loading_animation_widget: ^1.2.0+4
  flutter_animate: ^4.2.0+1
  animate_gradient: ^0.0.2+1
  lottie: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
      - assets/
      - assets/images/
      - assets/animations/

  fonts: 
      - family: Open Sans
        fonts: 
          - asset: assets/fonts/OpenSansBold.ttf
            weight: 700
          - asset: assets/fonts/OpenSansRegular.ttf
            weight: 400
          - asset: assets/fonts/OpenSansSemiBold.ttf
            weight: 600
      - family: SFNSDisplay
        fonts:
          - asset: assets/fonts/SFNSDisplayRegular.otf
      - family: CanelaText
        fonts:
          - asset: assets/fonts/CanelaTextRegular.otf
      - family: Charter
        fonts:
         - asset: assets/fonts/CharterRegular.otf
      - family: Palatino
        fonts:
        - asset: assets/fonts/PalatinoRegular.ttf
      - family: ProximaNova
        fonts:
        - asset: assets/fonts/ProximaNovaRegular.otf